import mongoose from 'mongoose';

// ---------------------------------------------------------------------------
// ScanLog = append-only audit of EVERY gate scan attempt, successful or
// rejected. It answers "who scanned what, at which gate, when, and why did it
// fail" long after the fact.
//
// APPEND ONLY. This collection must never be updated or deleted by the
// application, and no update/delete API may be added for it. It is also NOT
// the source of movement state - the Movement document is. Rejected attempts
// live here (a separate collection) rather than in `movements` because they
// have a completely different shape (no state, no movement timestamps) and
// because the unique "one movement per outpass" invariant there must stay
// intact while rejections are still fully audited.
//
// Writing a log row must never be able to break a legitimate scan: the scan
// service treats it as fire and forget, exactly like notifyNewOutpass() in
// server/services/notificationService.js.
//
// Everything here is a SNAPSHOT taken at scan time (student and gate details
// are copied, not joined), so the audit stays readable after a profile change,
// a gate rename, or the HOD monthly delete of the Outpass documents.
// ---------------------------------------------------------------------------

// What the server decided the attempt was. A RETURN attempt that turns out to
// have no EXIT recorded is still logged as 'RETURN' and rejected; 'UNKNOWN' is
// only the fallback for an attempt that could not be classified at all (for
// example an unreadable or foreign QR code).
export const SCAN_ACTIONS = ['EXIT', 'RETURN', 'UNKNOWN'];

export const SCAN_RESULTS = ['SUCCESS', 'REJECTED'];

// Stable machine readable rejection codes. They are deliberately an enum, so a
// typo can never be stored as a valid reason and rejection analytics can group
// attempts reliably. Adding a code requires a conscious model change.
export const SCAN_REASONS = [
  '',
  'TIME_NOT_STARTED',
  'ALREADY_SCANNED',
  'NO_APPROVED_OUTPASS',
  'OUTPASS_NOT_USABLE',
  'NO_EXIT_RECORDED',
  'GATE_INACTIVE',
  'INVALID_GATE_TOKEN',
  'ALREADY_OUTSIDE',
  'WINDOW_UNRESOLVABLE',
];

const scanLogSchema = new mongoose.Schema(
  {
    // Nullable: an attempt can fail before it resolves to an outpass (invalid
    // QR code, no approved outpass), and the referenced outpass may later be
    // deleted by the HOD monthly delete. The snapshots below keep the row
    // readable in both cases, so nothing may ever depend on this reference
    // resolving.
    outpass: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Outpass',
      default: null,
    },
    outpassId: {
      type: String,
      trim: true,
      default: '',
    },
    // Who attempted. Always the authenticated student read from the JWT.
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    registerNumber: {
      type: String,
      trim: true,
      default: '',
    },
    studentName: {
      type: String,
      trim: true,
      default: '',
    },
    // Which gate was scanned. Nullable for an unknown / invalid token, and the
    // code/name are snapshots so a later gate rename cannot rewrite history.
    gate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Gate',
      default: null,
    },
    gateCode: {
      type: String,
      trim: true,
      default: '',
    },
    gateName: {
      type: String,
      trim: true,
      default: '',
    },
    action: {
      type: String,
      enum: SCAN_ACTIONS,
      default: 'UNKNOWN',
      required: true,
    },
    // Required with NO default on purpose: an audit row must always state
    // explicitly whether the scan succeeded, so a forgotten value fails loudly
    // instead of silently recording a success.
    result: {
      type: String,
      enum: SCAN_RESULTS,
      required: true,
    },
    // Empty for successful scans; one of the stable codes above for rejections.
    reason: {
      type: String,
      enum: SCAN_REASONS,
      default: '',
    },
    // The exact text the student was shown at that moment (an audit of what
    // was communicated, independent of later wording changes).
    message: {
      type: String,
      trim: true,
      default: '',
    },
    // Authoritative moment of the attempt, from the server clock. The scan
    // service passes the instant it captured at request start; the default is
    // only a safety net so an audit row can never be written without a time.
    occurredAt: {
      type: Date,
      required: true,
      default: Date.now,
    },
    // Diagnostics only (clock skew detection). NEVER used for validation.
    clientReportedAt: {
      type: Date,
      default: null,
    },
    // Optional idempotency key generated by the scanner page, so a double tap
    // or a retried request cannot create two audit rows for one physical scan.
    // It is NOT stored as null when the client does not send one: a sparse
    // unique index DOES index explicit nulls, which would allow only a single
    // null row and then fail every later insert. The setter below keeps the
    // path absent instead, which is what makes the sparse unique index safe.
    clientScanId: {
      type: String,
      trim: true,
      set: (value) => {
        if (value === null || value === undefined) {
          return undefined;
        }
        const text = String(value).trim();
        return text === '' ? undefined : text;
      },
    },
    deviceInfo: {
      type: String,
      trim: true,
      default: '',
    },
  },
  {
    timestamps: true,
  }
);

// Recent activity feed / admin audit view.
scanLogSchema.index({ createdAt: -1 });

// Full attempt timeline for one outpass ("why was my scan rejected?").
scanLogSchema.index({ outpass: 1, createdAt: 1 });

// One student's attempt history and abuse review.
scanLogSchema.index({ student: 1, createdAt: -1 });

// Gate level activity and failure investigation.
scanLogSchema.index({ gate: 1, createdAt: -1 });

// Rejection analytics: which rules fail most, and at which gate.
scanLogSchema.index({ result: 1, reason: 1, createdAt: -1 });

// Idempotency for retried scans. Sparse so rows without a clientScanId are
// simply not indexed (see the setter comment above).
scanLogSchema.index({ clientScanId: 1 }, { unique: true, sparse: true });

const ScanLog = mongoose.model('ScanLog', scanLogSchema);

export default ScanLog;

