import Gate, { GATE_TOKEN_PREFIX } from '../models/Gate.js';

// ---------------------------------------------------------------------------
// Gate administration - the backend foundation for the permanent gate QR.
//
// A Gate is the physical hostel/campus gate and owns ONE permanent QR. These
// endpoints only CREATE gates, READ gate information and hand out the permanent
// QR PAYLOAD. They never scan anything, and they never return student or
// outpass data (the QR belongs to the GATE, not to a person or a request).
//
// Exposure rules:
//   - `qrToken` is NEVER read from the client. The Gate model assigns it on
//     creation (server/models/Gate.js pre-validate hook), so a caller - even an
//     authenticated administrator - cannot supply, guess or overwrite a gate's
//     permanent QR value.
//   - The token is also kept OUT of the gate information shape below. It is
//     only returned by GET /api/gates/:id/qr as the final `qrPayload`, so a gate
//     listing can never leak the value printed at the gate.
//   - Every response is hand-built (never a raw Mongoose document), so internal
//     fields such as __v, and the token, cannot leak by accident.
// ---------------------------------------------------------------------------

// The single gate information shape used by the read/create responses.
// Deliberately excludes qrToken - see the exposure rules above.
const toGateResponse = (gate) => ({
  _id: gate._id,
  code: gate.code,
  name: gate.name,
  hostelName: gate.hostelName || '',
  location: gate.location || '',
  active: gate.active !== false,
  createdAt: gate.createdAt,
  updatedAt: gate.updatedAt,
});

// `active` accepts a JSON boolean. The two string forms are tolerated as well,
// so a form encoded body cannot silently flip an intentionally disabled gate
// back to true. Anything else (undefined included) falls through to the model
// default (true).
const parseActive = (value) => {
  if (typeof value === 'boolean') return value;
  if (value === 'true') return true;
  if (value === 'false') return false;
  return undefined;
};

// POST /api/gates  (HOD only)
// Creates one gate. The permanent qrToken is generated by the Gate model.
export const createGate = async (req, res, next) => {
  try {
    const { code, name, hostelName, location, active } = req.body || {};

    if (!code || !String(code).trim()) {
      return res.status(400).json({ message: 'Gate code is required.' });
    }
    if (!name || !String(name).trim()) {
      return res.status(400).json({ message: 'Gate name is required.' });
    }

    // Whitelisted input ONLY. `qrToken` is intentionally absent from this list,
    // so a client supplied token can never be applied to a gate.
    const gate = await Gate.create({
      code: String(code).trim(),
      name: String(name).trim(),
      hostelName: typeof hostelName === 'string' ? hostelName.trim() : '',
      location: typeof location === 'string' ? location.trim() : '',
      active: parseActive(active),
    });

    res.status(201).json(toGateResponse(gate));
  } catch (error) {
    // A missing/invalid field and a duplicate gate code are client mistakes,
    // not server failures, so they answer 400 like the rest of the project.
    if (error.name === 'ValidationError') {
      const details = Object.values(error.errors || {})
        .map((item) => item.message)
        .join(' ');
      return res.status(400).json({ message: details || 'Invalid gate data.' });
    }
    if (error.code === 11000) {
      return res.status(400).json({ message: 'A gate with this code already exists.' });
    }
    next(error);
  }
};

// GET /api/gates  (staff read)
// Optional ?active=true|false uses the model's { active, hostelName } index.
export const listGates = async (req, res, next) => {
  try {
    const filter = {};
    if (req.query?.active === 'true') filter.active = true;
    if (req.query?.active === 'false') filter.active = false;

    const gates = await Gate.find(filter).sort({ code: 1 }).lean();
    res.json(gates.map(toGateResponse));
  } catch (error) {
    next(error);
  }
};

// GET /api/gates/:id  (staff read)
export const getGateById = async (req, res, next) => {
  try {
    const gate = await Gate.findById(req.params.id).lean();

    if (!gate) {
      return res.status(404).json({ message: 'Gate not found' });
    }

    res.json(toGateResponse(gate));
  } catch (error) {
    // A malformed id simply does not identify a gate.
    if (error.name === 'CastError') {
      return res.status(404).json({ message: 'Gate not found' });
    }
    next(error);
  }
};

// GET /api/gates/:id/qr  (HOD / Warden)
// The permanent QR payload in the agreed format: HOMS1:<opaque-gate-token>.
// It carries the GATE identity only - no student, no outpass, no JWT, no
// session - so a photographed QR reveals nothing about any person.
export const getGateQrPayload = async (req, res, next) => {
  try {
    // Narrow projection: the token is loaded only in this one handler.
    const gate = await Gate.findById(req.params.id)
      .select('code name hostelName active qrToken')
      .lean();

    if (!gate) {
      return res.status(404).json({ message: 'Gate not found' });
    }

    if (!gate.qrToken) {
      // Defensive: a gate must never produce "HOMS1:undefined" - a printed QR
      // that cannot be resolved would break every scan at that gate.
      return res.status(409).json({
        message: 'This gate has no QR token and cannot be printed yet.',
      });
    }

    res.json({
      _id: gate._id,
      code: gate.code,
      name: gate.name,
      hostelName: gate.hostelName || '',
      active: gate.active !== false,
      qrPayload: `${GATE_TOKEN_PREFIX}${gate.qrToken}`,
    });
  } catch (error) {
    if (error.name === 'CastError') {
      return res.status(404).json({ message: 'Gate not found' });
    }
    next(error);
  }
};
